print ("*****************")
print ("*** VARIABLES ***")
print ("*****************")
print ("En Python3 existen 3 tipos de datos: ")
print ("Enteros (int); Decimales (float) y Complejos (Complex)")
print ("*****************")
Entero=int(input("Coloca un numero entero: "))
Decimal=float(input("Coloca un numero decimal: "))
Complejo=complex(input("Coloca un numero complejo (Ejemplo: 1+2j): "))
print ("El numero entero es: ",Entero)
print ("El numero decimal es: ",Decimal)
print ("El numero complejo es: ",Complejo)
input()
