print ("************************")
print ("*** TIPOS DE ENTRADA ***")
print ("************************")
Entero1=int(input("Coloca el año de tu nacimiento: "))
Decimal1=float(input("Coloca el valor de la constante de euler: "))
Cadena1=input("Coloca el nombre de tu pais de origen: ")
print()
print(Entero1)
print(Decimal1)
print(Cadena1)
print()
Entero2=input("Coloca tu edad: ")
Decimal2=int(input("Coloca el valor de la constante pi: "))
Cadena2=float(input("Coloca tu nombre: "))
print()
print(Entero2)
print(Decimal2)
print(Cadena2)
