def Texto():
    print ("***********************************************************")
    print ("SALIDA DE TEXTO")
    print("print(\"Hola\")                = Hola")
    print("print(\'Hola\')                = Hola")
    print("print(\"Hola\",\"Adios\")        = Hola")
    print("                               Adios")
    print("print(\"Hola\")")
    print("print()")
    print("print(\"Adios\")               = Hola")
    print ()
    print ("                               Adios")
    print("print(\"Hola\", end=\" \")")
    print("print(\" y adios\")            = Hola y adios")
    print ("***********************************************************")
def Variables():
    print ("SALIDA DE VARIABLES")
    print("print(\"Valor de la variable la suma: \",suma)       = 15")
    print("print(\"Soy\",Nombre,\"y tengo\",Edad,\"años\")          = Soy Ruben y tengo 19 años")
    print("print(\"Soy\"+Nombre+\"y tengo\"+Edad+\"años\")          = Soy Ruben y tengo 19 años")
    print ("***********************************************************")
def Numeros():
    print ("SALIDA DE NUMEROS")
    print("print(int(2.9))               = 2")
    print("print(float(2))               = 2.0")
    print ("***********************************************************")
#
print ("***********************")
print ("*** SALIDA DE DATOS ***")
print ("***********************")
Texto()
Variables()
Numeros()
input ()